import { TestResult } from "./TestResult";

/**
 * ExecutionReport
 *
 * Represents the final reporting artifact generated by the
 * Quality Dashboard reporting engine.
 *
 * This model consolidates execution results, execution context,
 * diagnostics, failure intelligence, and business insights into
 * a single source of truth.
 *
 * Generated File:
 *
 * reports/latest/execution-report.json
 *
 * Data Sources:
 *
 * - playwright-results.json
 * - execution-flow.json
 *
 * Current Responsibilities:
 *
 * - Execution summary
 * - Test results
 * - Execution statistics
 * - Failure diagnostics
 * - Root cause analysis
 * - Business impact visibility
 * - Test data correlation
 *
 * Architecture:
 *
 * playwright-results.json
 *             │
 *             ▼
 * PlaywrightResultsParser
 *             │
 *             ▼
 * ExecutionContextParser
 *             │
 *             ▼
 * ExecutionReport
 *             │
 *             ▼
 * execution-report.json
 *
 * Current Sections:
 *
 * - execution information
 * - summary
 * - statistics
 * - test results
 *
 * Dashboard Usage:
 *
 * The React dashboard consumes this artifact directly and
 * should not access Playwright raw artifacts.
 *
 * Future Evolution:
 *
 * Additional sections may be introduced:
 *
 * - timeline
 * - topFailures
 * - recommendedActions
 * - qualityInsights
 * - historicalMetrics
 * - aiAnalysis
 *
 * Key Principle:
 *
 * This model represents the primary contract between
 * the reporting engine and all future consumers
 * (Dashboard, APIs, AI services, and agents).
 */
export interface ExecutionReport {
    executionId: string;
    project: string;
    executionDate: string;

    passed: number;
    failed: number;
    skipped: number;

    duration: number;

    summary: {

        totalTests: number;

        executedTests: number;

        successRate: number;

        executionStatus: string;
    };

    tests: TestResult[];

    statistics: {

        flows: number;

        actions: number;

        successes: number;

        dataEvents: number;

        errors: number;
    };
}