/**
 * Represents a structured semantic execution failure
 * generated by the execution observability system.
 *
 * Purpose:
 * - Normalize raw runtime errors
 * - Provide human-readable execution failures
 * - Provide machine-readable telemetry
 * - Enrich failures with contextual technical information
 *
 * This structure is generated by ErrorInterpreter
 * and later persisted into execution-flow.json.
 *
 * These execution errors can later be used for:
 * - debugging
 * - execution timelines
 * - HTML reports
 * - AI-powered analysis
 * - root cause analysis
 * - flaky test investigation
 * - explainable execution telemetry
 *
 * Design Goals:
 * - readable
 * - structured
 * - contextual
 * - incremental
 * - observability-friendly
 */
export interface ParsedExecutionError {

  /**
   * Main technical execution message.
   *
   * Example:
   * - locator.waitFor timeout exceeded
   */
  message: string;

  /**
   * Human-readable operational summary.
   *
   * Example:
   * - Timeout while waiting for "First Name" to become visible.
   */
  summary: string;

  /**
   * Simplified semantic error classification.
   *
   * Example:
   * - timeout exceeded
   * - element(s) not found
   */
  error?: string;

  /**
   * Structured technical execution context.
   *
   * These details provide grounded technical evidence
   * that can later be used for:
   * - debugging
   * - AI analysis
   * - HTML reports
   * - execution investigation
   */
  technicalContext?: {

    /**
     * Original locator or target involved in the failure.
     */
    locator?: string;

    /**
     * Configured timeout associated with the failure.
     */
    timeout?: string;

    /**
     * Human-readable technical failure reason.
     */
    reason?: string;
  };

  /**
 * Original test file where the execution failure propagated.
 */
  originTestFile?: string;

  /**
   * Simplified semantic execution trace.
   */
  stackTraceSummary?: string[];
}