import fs from 'fs';
import path from 'path';

import { ExecutionContextParser } from '@/reporting/services/ExecutionContextParser';

/**
 * ReportGenerator
 *
 * Responsibility:
 * Generate the final execution-report.json artifact consumed
 * by the Quality Dashboard and future reporting integrations.
 *
 * This class represents the final step of the reporting pipeline.
 *
 * Reporting Pipeline:
 *
 * playwright-results.json
 *         │
 *         ▼
 * PlaywrightResultsParser
 *         │
 *         ▼
 * ExecutionContextParser
 *         │
 *         ▼
 * ExecutionReport
 *         │
 *         ▼
 * execution-report.json
 *
 * Responsibilities:
 *
 * - Instantiate ExecutionContextParser
 * - Generate the ExecutionReport object
 * - Create the output directory if necessary
 * - Persist execution-report.json
 *
 * Output:
 *
 * reports/latest/execution-report.json
 *
 * Notes:
 *
 * This class does not perform any analysis,
 * enrichment, or diagnostics.
 *
 * Its sole responsibility is to persist the final
 * report generated by the reporting engine.
 */

export class ReportGenerator {

    public generate(): void {

        const parser = new ExecutionContextParser();

        const report = parser.parse();

        const outputDirectory = path.join(
            process.cwd(),
            'reports',
            'latest'
        );

        fs.mkdirSync(outputDirectory, {
            recursive: true
        });

        const outputFile = path.join(
            outputDirectory,
            'execution-report.json'
        );

        fs.writeFileSync(
            outputFile,
            JSON.stringify(report, null, 2),
            'utf8'
        );

        console.log(`Report generated: ${outputFile}`);
    }
}